version: '3.3'
services:
  # elasticsearch:
  #   build:
  #     context: elasticsearch/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - type: bind
  #       source: ./elasticsearch/config/elasticsearch.yml
  #       target: /usr/share/elasticsearch/config/elasticsearch.yml
  #       read_only: true
  #     - type: volume
  #       source: datn-bknews
  #       target: /usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     ELASTIC_PASSWORD: "tienanh138"
  #   networks:
  #     - datn-bknews

  # logstash:
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - type: bind
  #       source: ./logstash/config/logstash.yml
  #       target: /usr/share/logstash/config/logstash.yml
  #       read_only: true
  #     - type: bind
  #       source: ./logstash/pipeline
  #       target: /usr/share/logstash/pipeline
  #       read_only: true
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   expose: 
  #     - "5044"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - datn-bknews
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   build:
  #     context: kibana/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   environment:
  #       ELASTICSEARCH_USERNAME: kibana
  #       ELASTICSEARCH_URL: http://elasticsearch:9200
  #       ELASTICSEARCH_PASSWORD: "tienanh138"
  #   #   ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpaM1YzQVpTMFFVNmhQU3UzczlmLUpn
  #   volumes:
  #     - type: bind
  #       source: ./kibana/config/kibana.yml
  #       target: /usr/share/kibana/config/kibana.yml
  #       read_only: true
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - datn-bknews
  #   depends_on:
  #     - elasticsearch

  # filebeat:
  #   build: ./filebeat
  #   entrypoint: "filebeat -e -strict.perms=false"
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #   networks:
  #     - datn-bknews
  #   depends_on: 
  #     - logstash
  #     - elasticsearch
  #     - kibana
  #   links: 
  #     - logstash


  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./nginx/config:/etc/nginx/conf.d
  #     - ./nginx/log:/var/log/nginx
  #   ports:
  #     - "3000:80"
  #     - "3003:443"
  #   links:
  #     - app-project20231:app-project20231
  #   depends_on: 
  #     - app-project20231
  #   networks:
  #     - project20231

  bknews-client:
    build : 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
      - ./app/log:/var/log/app
      - /usr/src/app-fe/node_modules/
    command: npm start
    ports:
      - "3000:3000"
    depends_on: 
      - bknews-server
    networks:
      - datn-bknews

  bknews-server:
    build : 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
      - ./app/log:/var/log/app
      - /usr/src/app/node_modules/
    command: npm start
    ports:
      - "3003:3003"
    networks:
      - datn-bknews

  bknews-crawler:
    build : 
      context: ./crawler
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
      - ./app/log:/var/log/app
      - /usr/src/app/node_modules/
    command: npm start
    ports:
      - "3003:3003"
    depends_on: 
      - bknews-server
    networks:
      - datn-bknews

networks:
  datn-bknews:
    driver: bridge
volumes:
  elasticsearch_datn-bknews: